src/main/java/com/bwfcwalshy/flarebot/github/GithubListener.java
Yegh showing the path didn't look good.
=> Made it not show the path.

src/main/java/stream/flarebot/flarebot/commands/general/JoinCommand.java, src/main/java/stream/flarebot/flarebot/commands/general/LeaveCommand.java
- `summon` alias for join command
- `gtfo`, `getout` and `banish` aliases for leave command
**N/A**
=> Add aliases for join and leave

src/main/java/stream/flarebot/flarebot/github/GithubListener.java, src/main/java/stream/flarebot/flarebot/util/MessageUtils.java
Lines in github file
Limit to last 5 commits
Limit messages to 80 characters
=> Make GitHub webhook better

src/main/java/stream/flarebot/flarebot/commands/moderation/PermissionsCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/TestCommand.java
Mass adding of groups via roles
Switched test command over to sending a file (we hit the limit!)
=> Role mass add (also test comamnd stuff)

pom.xml, src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/commands/secret/ShardRestartCommand.java
Pin message when reacted 5 times with :pushpin: 
Updated JDA
Fixed `shutdown()` error
=> Pin stuff and General Fixes

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/moderation/mod/MuteCommand.java, src/main/java/stream/flarebot/flarebot/mod/AutoModConfig.java, src/main/java/stream/flarebot/flarebot/mod/Punishment.java
I re-enabled modlog and also made it look nicer
=> Modlog stuffs

src/main/java/stream/flarebot/flarebot/FlareBot.java
=> #NoIDESucks

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/FlareBotManager.java, src/main/java/stream/flarebot/flarebot/commands/general/TagsCommand.java, src/main/java/stream/flarebot/flarebot/commands/music/LoadCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/GuildCommand.java, src/main/java/stream/flarebot/flarebot/objects/GuildWrapper.java, src/main/java/stream/flarebot/flarebot/permissions/PerGuildPermissions.java, src/main/java/stream/flarebot/flarebot/util/MessageUtils.java
* Added TagsCommand.java
* Changed excessive load time to 200ms
* Permissions for contributors changed - internal review needed
* Changed MessageUtils sendMessage params to better fit our needs
* Fixed load prefix issue
* Fixed time to be UTC in MessageUtils
=> Added tags, cleaned up code and fixed bugs

.gitignore, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/secret/AnnounceCommand.java
- [my laptop cant launch the bot] All changes have been tested
AnnounceCommand.java
FlareBot.java
.gitignore
=> Stop people from spamming Updates

src/main/java/stream/flarebot/flarebot/commands/moderation/mod/WarningsCommand.java
=> Fixed compliaction issues

src/main/java/stream/flarebot/flarebot/FlareBotManager.java, src/main/java/stream/flarebot/flarebot/commands/general/ReportCommand.java, src/main/java/stream/flarebot/flarebot/objects/Report.java, src/main/java/stream/flarebot/flarebot/objects/ReportMessage.java, src/main/java/stream/flarebot/flarebot/objects/ReportStatus.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java, src/main/java/stream/flarebot/flarebot/util/ReportManager.java
N/A
Switched from using jda messages as the report messages to using a new object.
N/A
N/A
The Changed listed above fixes gson getting stuck in an infinite loop because JDAs messages caused that
N/A
=> Fixed gson freeze

src/main/java/stream/flarebot/flarebot/commands/moderation/PermissionsCommand.java, src/main/java/stream/flarebot/flarebot/objects/GuildWrapper.java, src/main/java/stream/flarebot/flarebot/permissions/PerGuildPermissions.java
permissions reset
permissions restoredefault
Moved Permissions usage over to an embed. (It was getting to big)
N/A
N/A
A small typo
N/A
=> Misc perms things

src/main/java/stream/flarebot/flarebot/FlareBot.java
=> Fix songnick DM spam

README.md
N/A
Added walshy to current maintainers and changed current contribs to current maintainers
N/A
N/A
N/A
N/A
=> Change Contributing Corner a bit

src/main/java/stream/flarebot/flarebot/commands/general/PollCommand.java, src/main/java/stream/flarebot/flarebot/commands/general/SelfAssignCommand.java, src/main/java/stream/flarebot/flarebot/commands/general/TagsCommand.java, src/main/java/stream/flarebot/flarebot/objects/GuildWrapper.java, src/main/java/stream/flarebot/flarebot/permissions/PerGuildPermissions.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java
- `t` as an alias for tags
- `flarebot.playlist.clear` is now default
N/A
N/A
- Fixed NPE in warnings command
- Catch non-number is poll open command
N/A
=> General fixes

src/main/java/stream/flarebot/flarebot/Events.java
N/A
N/A
N/A
N/A
Refer to this trello card: [link](https://trello.com/c/o00LK2Qz)
N/A
=> Fixed bot leaving vc issue

src/main/java/stream/flarebot/flarebot/commands/general/InfoCommand.java, src/main/java/stream/flarebot/flarebot/commands/general/StatsCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/PostUpdateCommand.java
- Ability to view multiple pieces of data in `_stats` and `_info` using a command to separate values
- `pr:<prNum>` to `_postupdate` **DEV ONLY**
=> Better PostUpdate command and Multiple stats & info args

src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java
=> Monitor Avg Delete Message Time

src/main/java/stream/flarebot/flarebot/commands/moderation/PermissionsCommand.java
=> Logicccccccc

src/main/java/stream/flarebot/flarebot/commands/moderation/PermissionsCommand.java
An issue where we where trying to get an argument that didn't exist
=> Perm arg hotfix

src/main/java/stream/flarebot/flarebot/ModlogEvents.java, src/main/java/stream/flarebot/flarebot/commands/moderation/LockChatCommand.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java, src/main/java/stream/flarebot/flarebot/util/errorhandling/Filter.java, src/main/java/stream/flarebot/flarebot/util/objects/expiringmap/ExpiringMap.java, src/main/resources/logback.xml
- Useless error in resolving videos
- Handle AuditLog errors for banning
- NPE in LockChatCommand
- Handle concurrency in ExpiringMap
- Permissions args errors
=> Hotfix 4.1.0.1

src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/ModlogEvents.java
* One error with message edit in startup
* Fixed role delete causing an NPE
=> Missing cannotHandle

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/mod/modlog/ModlogHandler.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java
Added a bunch of null checks so the bot could actually load.
=> null hotfix

src/main/java/stream/flarebot/flarebot/commands/moderation/mod/TempBanCommand.java
Args in TempBanCommand.java for ModlogHandler.getInstance().handleAction()
=> Fixed args for handleAction()

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/moderation/PurgeCommand.java, src/main/java/stream/flarebot/flarebot/commands/useful/TagsCommand.java, src/main/java/stream/flarebot/flarebot/mod/modlog/ModlogHandler.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java
- Raw tag subcommand to display the "raw" contents of a tag
- Permissions check in sending modlog
=> v4.1.3 Hotfix 

build.gradle, pom.xml, src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/CommandType.java, src/main/java/stream/flarebot/flarebot/commands/informational/BetaCommand.java, src/main/java/stream/flarebot/flarebot/commands/informational/DonateCommand.java, src/main/java/stream/flarebot/flarebot/commands/moderation/mod/UnbanCommand.java, src/main/java/stream/flarebot/flarebot/commands/music/SkipCommand.java, src/main/java/stream/flarebot/flarebot/mod/Moderation.java, src/main/java/stream/flarebot/flarebot/mod/modlog/ModlogHandler.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java, src/main/java/stream/flarebot/flarebot/util/MessageUtils.java, src/main/java/stream/flarebot/flarebot/util/UsageParser.java, src/main/java/stream/flarebot/flarebot/util/errorhandling/ExceptionWrapper.java
- New informational commands! `_beta` and `_donate`
- `_usage` now shows whether the command is beta or not
- Make skip logic better (Based on number of votes rather than people)
- Fix the long-standing bug of the bot not leaving if you move it or if another user is moved
- Fix startup errors
- Unban force-get bug
- Modlog duping bug
=> Few long standing bugs - v4.1.4

src/main/java/stream/flarebot/flarebot/commands/moderation/LockChatCommand.java, src/main/java/stream/flarebot/flarebot/commands/music/ResumeCommand.java, src/main/java/stream/flarebot/flarebot/mod/modlog/ModlogHandler.java, src/main/java/stream/flarebot/flarebot/music/extractors/YouTubeSearchExtractor.java, src/main/java/stream/flarebot/flarebot/objects/GuildWrapper.java
* Some logic in LockChatCommand
* Reason being empty when only a channel is passed
* Muted users can still talk in some channels
* Tempmute not unmuting
=> Basic improvements - 4.1.6

.gitignore, build.gradle, pom.xml, src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/GitHandler.java, src/main/java/stream/flarebot/flarebot/ModlogEvents.java, src/main/java/stream/flarebot/flarebot/commands/general/InfoCommand.java, src/main/java/stream/flarebot/flarebot/commands/moderation/PurgeCommand.java, src/main/java/stream/flarebot/flarebot/music/VideoThread.java, src/main/resources/sentry.properties
- GitHandler to manage git
- Sentry settings are now *all* set programmatically
- Sentry release is now set to the git commit hash not the version #
- Not taking into account channel overrides for perms
- Audit log optimisation
=> Some lovely jubly hotfixes

src/main/java/stream/flarebot/flarebot/util/objects/expiringmap/ExpiringMap.java
=> Document ExpiringMap

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/music/QueueCommand.java
- `QueueCommand` from `PlayCommand`
- `_playlist` in favour of `_queue`
=> Deprecate playlist and move to queue

src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/GitHandler.java, src/main/java/stream/flarebot/flarebot/util/MessageUtils.java, src/main/java/stream/flarebot/flarebot/util/ShardUtils.java, src/main/java/stream/flarebot/flarebot/util/WebUtils.java
=> Documentation

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/FlareBotManager.java, src/main/java/stream/flarebot/flarebot/analytics/ActivityAnalytics.java, src/main/java/stream/flarebot/flarebot/analytics/AnalyticSender.java, src/main/java/stream/flarebot/flarebot/analytics/AnalyticsHandler.java, src/main/java/stream/flarebot/flarebot/analytics/GuildAnalytics.java, src/main/java/stream/flarebot/flarebot/analytics/GuildCountAnalytics.java, src/main/java/stream/flarebot/flarebot/api/ApiRoute.java, src/main/java/stream/flarebot/flarebot/api/DefaultCallback.java, src/main/java/stream/flarebot/flarebot/util/Constants.java, src/main/java/stream/flarebot/flarebot/util/WebUtils.java
This adds analytics to the bot, this is data which will be posted to the API and will be turned into a much nicer way to track analytics. There's some basic analytic classes right now and I will probably add more with time but this is more a proof of concept.
=> Proposal - analytics

src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/commands/useful/RemindCommand.java, src/main/java/stream/flarebot/flarebot/scheduler/FutureAction.java
Dm remind option
Remind list
Remind clear
=> Expand reminders, allow DM notifications, listing and clearing

src/main/java/stream/flarebot/flarebot/commands/moderation/PermissionsCommand.java, src/main/java/stream/flarebot/flarebot/permissions/PerGuildPermissions.java
Perms hierarchy moving
Made group interaction none case sensitive
Cleaned up the command a bit
=> Perms hierarchy moving

.gitignore, build.gradle, pom.xml, src/main/java/stream/flarebot/flarebot/Events.java, src/main/java/stream/flarebot/flarebot/FlareBot.java, src/main/java/stream/flarebot/flarebot/FlareBotManager.java, src/main/java/stream/flarebot/flarebot/GitHandler.java, src/main/java/stream/flarebot/flarebot/ModlogEvents.java, src/main/java/stream/flarebot/flarebot/analytics/GuildAnalytics.java, src/main/java/stream/flarebot/flarebot/api/GzipRequestInterceptor.java, src/main/java/stream/flarebot/flarebot/commands/moderation/AutoAssignCommand.java, src/main/java/stream/flarebot/flarebot/commands/music/SkipCommand.java, src/main/java/stream/flarebot/flarebot/commands/random/JumboCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/DebugCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/EvalCommand.java, src/main/java/stream/flarebot/flarebot/commands/secret/TestCommand.java, src/main/java/stream/flarebot/flarebot/mod/modlog/ModlogHandler.java, src/main/java/stream/flarebot/flarebot/scheduler/FutureAction.java, src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java, src/main/java/stream/flarebot/flarebot/util/MessageUtils.java, src/main/java/stream/flarebot/flarebot/util/WebUtils.java, src/main/java/stream/flarebot/flarebot/web/DataInterceptor.java
Just a pr to merge master into 4.2
=> Merge master

src/main/java/stream/flarebot/flarebot/commands/random/JumboCommand.java
makes it to where it matches the multi function
N/A
Added the same looks to emoji names to the single function to match the multi function
N/A
N/A
N/A
N/A
=> cosmetic change to emoji names in single function
